CREATE TABLE users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE rooms (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    building   VARCHAR(100) NOT NULL,
    capacity   INTEGER NOT NULL CHECK (capacity > 0),
    open_time  TIME NOT NULL,
    close_time TIME NOT NULL,
    CHECK (open_time < close_time)
);

CREATE TABLE bookings (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id    BIGINT NOT NULL REFERENCES rooms (id),
    user_id    BIGINT NOT NULL REFERENCES users (id),
    start_time TIMESTAMP NOT NULL,
    end_time   TIMESTAMP NOT NULL,
    status     VARCHAR(20) NOT NULL
               CHECK (status IN ('CONFIRMED', 'CANCELLED', 'COMPLETED')),
    CHECK (start_time < end_time)
);

CREATE INDEX idx_bookings_room_start ON bookings (room_id, start_time);
CREATE INDEX idx_bookings_user_start ON bookings (user_id, start_time);